version: '3.5'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sandbox
    ports:
      - "13306:3306"
    restart: always

  sandbox-app:
    image: sandbox
    container_name: sandbox-app
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "mysql-db"