package com.exadel.sandbox.team2.domain.enums;

public enum TelegramState {
    GIVE_PHONE_NUMBER, MAIN_MENU, GET_ACCOUNT_INFO,
    GET_CONTACT, SETTINGS, UPDATE_PHONE_NUMBER,
    MENU, CHOOSE_COUNTRY, CHOOSE_CITY, SHOW_OFFICES_BY_CITY,
    SHOW_WORKPLACES_BY_OFFICE, ASSIGN_BOOKING_TYPE,
    ONE_DAY_SELECT_DATE, CONTINUOUS_SELECT_DATE, RECURRING_SELECT_WEEK_DAY,
    BOOK_ONE_DAY_WORKPLACE, CHOOSE_LANGUAGE, SET_LANGUAGE, SELECT_END_DATE,
    SHOW_OFFICES_CONTINUOUS, SHOW_WORKPLACES_CONTINUOUS, GET_USER_BOOKINGS,
    RECURRING_DEFINE_WEEKDAYS, RECURRING_DEFINE_WEEKS, RECURRING_ASSIGN_END_WEEKDAY,
    RECURRING_ASSIGN_START_WEEKDAY, RECURRING_SHOW_WORKPLACES, CANCEL_BOOKING, DELETE_USER_BOOKING
}
