telegram:
  api:
    base:
      path: https://api.telegram.org/bot
  bot:
    username: ExadelTeam2OfficeBot
    token: 5178866872:AAGaxtgiG4-vJ5za7JEw1-RnbYV26DSGtSY
    webhook:
      webhook:
        setWebhookPath: '/setWebhook'
        webhookInfoPath: '/getWebhookinfo'
        path: https://cc0e-178-120-9-200.ngrok.io