telegram:
  api:
    base:
      path: 'https://api.telegram.org/bot'
  bot:
    username: 'ExadelTeam2LongPollingOfficeBot'
    token: '5150329244:AAE8hbBoNcQ60sH8tuGAR4I73b1xlbheK5k'
    webhook:
      setWebhookPath: '/setWebhook'
      webhookInfoPath: '/getWebhookinfo'
      path: 'https://cc0e-178-120-9-200.ngrok.io'