server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: sandbox
  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/sandbox?serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  profiles:
    active: dev

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG

telegrambot:
  botUsername: ExadelTeam2OfficeBot
  botToken: 5178866872:AAGaxtgiG4-vJ5za7JEw1-RnbYV26DSGtSY
  botPath: https://cc0e-178-120-9-200.ngrok.io

notification:
  mail:
    username: ${MAIL_USERNAME:bookingServiceExadelTeam2@gmail.com}
    password: ${MAIL_PASSWORD:AzizVladTeam2}
  properties:
    host: smtp.gmail.com
    port: 587
    auth: true
    starttls: true

authorization:
   secret: fgjdfhgjrfhsgkjhsdighehrgfsjhgfkdsjhuerghjfjdgsjkfhs
   expiration: 3600
