telegram:
  api:
    base:
      path: 'https://api.telegram.org/bot'
  bot:
    username: 'ExadelTeam2OfficeBot'
    token: '5178866872:AAGaxtgiG4-vJ5za7JEw1-RnbYV26DSGtSY'
    webhook:
      setWebhookPath: '/setWebhook'
      webhookInfoPath: '/getWebhookinfo'
      path: 'https://8118-94-158-61-201.ngrok.io/api/telegram'