INSERT INTO Role(name) VALUES ('USER');
INSERT INTO Role(name) VALUES ('SYSTEM');
INSERT INTO Role(name) VALUES ('MAP_EDITOR');
INSERT INTO Role(name) VALUES ('MANAGER');
INSERT INTO Role(name) VALUES ('ADMIN');